### ISSUE TITLE
By default send Dynatrace Events to both SERVICE & PGIs tagged with Keptn Tags

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#205] opened 2020-11-04 10:50 UTC
The Dynatrace Service by default uses the following attachRule when sending Deployment or Annotation Events to Dynatrace Entities:
```json
attachRules:
  tagRule:
  - meTypes:
    - SERVICE
    tags:
    - context: CONTEXTLESS
      key: keptn_project
      value: $PROJECT
    - context: CONTEXTLESS
      key: keptn_service
      value: $SERVICE
    - context: CONTEXTLESS
      key: keptn_stage
      value: $STAGE
```

With Dynatrace's new Release Inventory feature there is an initial focus on deployment events on PGIs vs SERVICE entities. This means that - when deploying services with Keptn the Dynatrace Service will send deployment events by default only to SERVICES which are then not shown in the new Release Inventory Screen.
I suggest to extend the default attachRules in helper.go:createAttachRules to also send it to a PGI

*Workaround:*
The workaround is to define these attach rules in the dynatrace.conf.yaml like this:
```json
---
spec_version: '0.1.0'
attachRules:
  tagRule:
  - meTypes:
    - SERVICE
    - PROCESS_GROUP_INSTANCE
    tags:
    - context: CONTEXTLESS
      key: keptn_project
      value: $PROJECT
    - context: CONTEXTLESS
      key: keptn_service
      value: $SERVICE
    - context: CONTEXTLESS
      key: keptn_stage
      value: $STAGE
```

**Comment by arthurpitman** [comment] 2021-05-31 12:39
Duplicate of #240

**Closed by arthurpitman** 2021-05-31 12:39 UTC
