### ISSUE TITLE
Tags from Dynatrace Problem not added to Keptn Problem Payload

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/dynatrace-service#221] opened 2021-01-11 08:56 UTC
When Dynatrace Service receives a problem from Dynatrace it will parse the Tags field to know for which keptn project, stage and service this problem should be assigned to. The tag field itself is then however removed from the actual problem details. This prevents some important remediation integration use cases, e.g: sending details to a notification tool such as OpsGenie where these tags are needed for proper routing

The ask here is that the dynatrace service forwards ALL problem details - including the Tags - to the Keptn Problem Event

**Comment by arthurpitman** [comment] 2021-05-31 12:36
Duplicate of #278

**Closed by arthurpitman** 2021-05-31 12:36 UTC
