### ISSUE TITLE
SLI broken when using filter expression

### ISSUE THREAD

**Issue by diegorqc** [keptn-contrib/dynatrace-service#393] opened 2021-06-02 00:07 UTC
When using an SLI definition with the filter expression the sli service fails to get the metric. 

Steps to recreate
Use the first SLI 
`rtp95:   "metricSelector=builtin:service.response.time&entitySelector=tag(keptn_project:simplenodeproject),tag(keptn_stage:staging),tag(keptn_service:simplenodeservice),type(SERVICE)"`
Adjust to your entity to get the response time

Use the same SLI filter base on and entity value or some other filter.
`   #rtp95: "metricSelector=builtin:service.response.time:filter(eq("dt.entity.service","SERVICE-6B5362A1398963FF"))&entitySelector=tag(keptn_project:simplenodeproject),tag(keptn_service:simplenodeservice),type(SERVICE)"`
This will give you an error about the sli and it would also break all the others SLI's defined.

I have tested this using different metrics with single and multiple dimensions. The queries are working fine when run against the  dynatrace API . i.e.

https://dynatraceurlenvr.live.com/api/v2/metrics/query?metricSelector=builtin:service.response.time:filter(eq("dt.entity.service","SERVICE-6B5362A1398963FF"))&entitySelector=tag(keptn_project:simplenodeproject),tag(keptn_service:simplenodeservice),type(SERVICE)&from=now-30m

The dynatrace-sli-service logs only shows a couple of lines with an unsupported error 
`{"timestamp":"2021-06-01T23:59:08.678016116Z","logLevel":"DEBUG","message":"No custom SLI for rtp95 found - Looking in defaults"}
{"timestamp":"2021-06-01T23:59:08.678019402Z","logLevel":"ERROR","message":"Error when fetching SLI config for rtp95 Unsupported SLI metric rtp95."}
{"timestamp":"2021-06-01T23:59:08.67802383Z","logLevel":"INFO","message":"Finished fetching metrics; Sending SLIDone event now ..."}
`

**Comment by arthurpitman** [comment] 2021-07-20 14:36
I'm closing this issue as I'm unable to reproduce the problem in the current version, provided the SLI file is valid YAML and the queries are correctly formed.

The following test cases work as expected (assuming a service `SERVICE-ABCD1234ABCD1234`):
* No filter, just entity selector:
  ```
  m0: metricSelector=builtin:service.response.time&entitySelector=tag(keptn_managed),tag(keptn_service:api-service),type(SERVICE)
  ```

* Just filter:
  ```
  m1: metricSelector=builtin:service.response.time:filter(eq("dt.entity.service","SERVICE-ABCD1234ABCD1234"))
  ```

* Escaped quotes inside quoted YAML value:
  ```
  m2: "metricSelector=builtin:service.response.time:filter(eq(\"dt.entity.service\",\"SERVICE-ABCD1234ABCD1234\"))"
  ```

* Filter and entity selector:
  ```
  m3: metricSelector=builtin:service.response.time:filter(eq("dt.entity.service","SERVICE-ABCD1234ABCD1234"))&entitySelector=tag(keptn_managed),tag(keptn_service:api-service),type(SERVICE)
  ```

The following test cases fail to return a value as expected, other SLIs defined in the same file continue to work:

* Missing quotes in `eq` condition:
  ```
  m4: metricSelector=builtin:service.response.time:filter(eq(dt.entity.service,SERVICE-ABCD1234ABCD1234))&entitySelector=tag(keptn_managed),tag(keptn_service:api-service),type(SERVICE)
  ```

* Non-existant service:
  ```
  m5: metricSelector=builtin:service.response.time:filter(eq("dt.entity.service","SERVICE-1234567890123455"))&entitySelector=tag(keptn_managed),tag(keptn_service:api-service),type(SERVICE)
  ```

Invalid YAML, e.g. with un-escaped inner quotes, causes the SLI file not to be loaded:  
  ```
  m6: "metricSelector=builtin:service.response.time:filter(eq("dt.entity.service","SERVICE-ABCD1234ABCD1234"))"
  ```

**Closed by arthurpitman** 2021-07-20 14:36 UTC
